### ISSUE TITLE
Generated io.hal contains 7i96 pin names

### ISSUE THREAD

**Issue by JetForMe** [jethornton/7i76e#2]
Thanks for this tool!

I tried using it to generate a configuration for my 7i76e, but it seems to be using 7i96 pin names. Trying to launch linuxcnc with it gives an error in `io.hal`:

```
# This file was created with the 7i96 Wizard on Jun 01 2019 22:41:21
# If you make changes to this file your screwed

net min-limit-home-joint-0 joint.0.neg-lim-sw-in <= hm2_7i96.0.gpio.006.in
net min-limit-home-joint-0 joint.0.home-sw-in
net max-limit-home-joint-0 joint.0.pos-lim-sw-in <= hm2_7i96.0.gpio.007.in
net max-limit-home-joint-0 joint.0.home-sw-in
net min-limit-home-joint-1 joint.1.neg-lim-sw-in <= hm2_7i96.0.gpio.008.in
net min-limit-home-joint-1 joint.1.home-sw-in
net min-limit-home-joint-1 joint.1.neg-lim-sw-in <= hm2_7i96.0.gpio.009.in
net min-limit-home-joint-1 joint.1.home-sw-in
net max-limit-home-joint-1 joint.1.pos-lim-sw-in <= hm2_7i96.0.gpio.0010.in
net max-limit-home-joint-1 joint.1.home-sw-in
```

Did I overlook some setting in the tabs, or is this a bug?

**Comment by jethornton** [comment]
Ok, thanks for the bug report. I guess I got distracted and forgot to change that.

JT

**Comment by jethornton** [comment]
Ok, I've fixed all that I could find and it does make a working configuration now.

JT

**Comment by JetForMe** [comment]
Thanks JT, that seems to have improved things, but it looks like the pin names are still wrong. They should be of the form `hm2_7i76e.0.7i76.0.0.input-04-not` or `hm2_7i76e.0.7i76.0.0.input-04`, but they're showing up as `hm2_7i76e.0.7i76.0.0.input-04.in`:

```
# This file was created with the 7i76e Wizard on Jun 02 2019 21:31:40
# If you make changes to this file your screwed

net min-limit-home-joint-0 joint.0.neg-lim-sw-in <= hm2_7i76e.0.7i76.0.0.input-04.in
net min-limit-home-joint-0 joint.0.home-sw-in
net max-limit-joint-0 joint.0.pos-lim-sw-in <= hm2_7i76e.0.7i76.0.0.input-05.in
net min-limit-home-joint-1 joint.1.neg-lim-sw-in <= hm2_7i76e.0.7i76.0.0.input-06.in
net min-limit-home-joint-1 joint.1.home-sw-in
net max-limit-joint-1 joint.1.pos-lim-sw-in <= hm2_7i76e.0.7i76.0.0.input-07.in
net max-limit-home-joint-2 joint.2.pos-lim-sw-in <= hm2_7i76e.0.7i76.0.0.input-08.in
net max-limit-home-joint-2 joint.2.home-sw-in
net min-limit-joint-2 joint.2.neg-lim-sw-in <= hm2_7i76e.0.7i76.0.0.input-09.in
net max-limit-home-joint-3 joint.3.pos-lim-sw-in <= hm2_7i76e.0.7i76.0.0.input-10.in
net max-limit-home-joint-3 joint.3.home-sw-in
```

**Comment by JetForMe** [comment]
JT, did you see my previous comment?

**Comment by jethornton** [comment]
Yep, sorry got busy and forgot to look into it.

JT

**Comment by JetForMe** [comment]
Np, thanks! I just have to be careful to fix them up each time I regenerate the files.

**Comment by jethornton** [comment]
If you run into anything else please start a new issue.

JT

**Comment by JetForMe** [comment]
Thanks for the quick fix! Of course, I will. This just seemed so closely related to the original issue I figured it was part of the same.
